### ISSUE TITLE
Request: Ability to reset a GlslPipeline to its initial state

### ISSUE THREAD

**Issue by matthen** [patriciogonzalezvivo/glsl-pipeline#1]
Currently there is no simple way to reset a GlslPipeline to its initial state, as when it is first created.

In its initial state we expect:
* `pipeline.frame = 0`
* `pipeline.lastTime = 0`
* `pipeline.time = 0`
* all buffers at initial values

This is useful e.g. for looping animations, where after a certain time you want to set time back to 0 and start again. Maybe there could be a method added like `pipeline.reset()`

**Comment by patriciogonzalezvivo** [comment]
Got it! super useful.
When you say buffers to their initial states, you mean cleaning all `u_doubleBufferN` ? Right? single `u_bufferN` don't have previous states.

**Comment by matthen** [comment]
Right
