### ISSUE TITLE
Breaks with latest version of react-three-fiber

### ISSUE THREAD

**Issue by bravokiloecho** [patriciogonzalezvivo/glsl-pipeline#9]
I've just updated my version of react-three-fiber to `"@react-three/fiber": "^8.17.5"` and now glsl-pipeline is causing the error:

```
Error: No OES_texture_float support for float textures.
```

**Comment by ammein** [comment]
Could you elaborate on the issue? Any example code I can refer to? How would you attach texture to the material? @bravokiloecho

**Comment by ammein** [comment]
Yesterday I tested your issue, it outputs an error like yours. But today it works like it should. Google Chrome solves the issue on hardware WebGL or ThreeJS library fixes the capabilities object not output the correct reading of GPU hardware capabilities of `floatFragmentTextures`. Upgrade your package and let me know if it fixes @bravokiloecho . It is best to keep your version intact in production like for example in `package.json` in `dependencies`:

```
threejs: ">=0.168.0 <1.0.0"
@react-three/fiber: ">=8.17.6 <9.0.0"
```

**Comment by ammein** [comment]
FYI @bravokiloecho , issue solved by merging one of my latest PR on latest ThreeJS code issue. Update your latest `glsl-pipeline` package and see if it is fixed. If it doesn't, you may file issue again.

Thanks

**Comment by bravokiloecho** [comment]
Thanks so much for looking into this @ammein! I've now upgraded my packages to these:

```
"@react-three/fiber": "^8.17.7",
"glsl-pipeline": "^3.0.0",
"three": "^0.168.0",
```

This has resolved the error I was finding before.

But it seems to have introduced a new one:

`TypeError: Cannot read properties of undefined (reading 'isInterleavedBufferAttribute')`

This is the full stack trace:

```
Call Stack
Object.update
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (13675:1)
Object.update
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (17490:1)
Object.update
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (17961:1)
projectObject
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (29955:1)
projectObject
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (30011:1)
projectObject
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (30011:1)
projectObject
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (30011:1)
projectObject
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (30011:1)
WebGLRenderer.render
node_modules/.pnpm/three@0.168.0/node_modules/three/build/three.module.js (29775:1)
render$1
node_modules/.pnpm/@react-three+fiber@8.17.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_three@0.168.0/node_modules/@react-three/fiber/dist/events-3515660a.esm.js (1544:1)
loop
node_modules/.pnpm/@react-three+fiber@8.17.7_react-dom@18.3.1_react@18.3.1__react@18.3.1_three@0.168.0/node_modules/@react-three/fiber/dist/events-3515660a.esm.js (1570:1)
```

**Comment by bravokiloecho** [comment]
Thank you so much @ammein ! That fixed it :) 

(if you saw my now deleted comment, ignore that; it was to do with a different issue)
